package com.empire.employeefinder.model.enums;

public enum JobTitle {
    HR_MANAGER,
    RECRUITMENT_SPECIALIST,
    TALENT_ACQUISITION_LEAD,
    HUMAN_RESOURCES_DIRECTOR,
    HEADHUNTER,
    TECHNICAL_RECRUITER,
    OPERATIONS_MANAGER,
    PROJECT_HIRING_COORDINATOR,
    STAFFING_CONSULTANT,
    CORPORATE_RECRUITMENT_PARTNER,
    ADMIN,
    SUPERADMIN
}

